name: Build and Upload EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use cloud-hosted Windows machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas speechrecognition matplotlib seaborn ttkthemes openpyxl pyaudio

      - name: Verify PyInstaller Installation
        run: pyinstaller --version  # Check if PyInstaller is installed correctly

      - name: Build EXE with All Dependencies
        run: |
          python -m PyInstaller --onefile --windowed --hidden-import pandas --hidden-import speech_recognition --hidden-import matplotlib --hidden-import seaborn --hidden-import ttkthemes --hidden-import openpyxl --hidden-import pyaudio --name ExcelFilterApp filter.py

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelFilterApp
          path: dist/ExcelFilterApp.exe
